Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -59,42 +59,42 @@ jobs:
           echo "Release Git Sha: ${{env.gitsha}}"
 
       # Set up JDK build environment
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
-        with:
-          distribution: 'temurin'
-          java-version: 17
+      # - name: Set up JDK 17
+      #   uses: actions/setup-java@v3
+      #   with:
+      #     distribution: 'temurin'
+      #     java-version: 17
         
       # Runs build steps
-      - name: Maven Package
-        run: mvn -ntp clean package
+      # - name: Maven Package
+      #   run: mvn -ntp clean package
         
-      - name: Maven Verify
-        run: mvn -ntp clean verify
+      # - name: Maven Verify
+      #   run: mvn -ntp clean verify
       
-      - name: Maven Spotless Check
-        run: mvn -ntp spotless:check
+      # - name: Maven Spotless Check
+      #   run: mvn -ntp spotless:check
       
       #Login to OpenShift Container Repository - Silver
-      - name: Login to OpenShift Container Repository - Silver
-        uses: docker/login-action@v2
-        with:
-          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER}}
-          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
-          password: ${{secrets.OPENSHIFT_SA_PASSWORD_SILVER}}
+      # - name: Login to OpenShift Container Repository - Silver
+      #   uses: docker/login-action@v2
+      #   with:
+      #     registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER}}
+      #     username: ${{secrets.OPENSHIFT_SA_USERNAME}}
+      #     password: ${{secrets.OPENSHIFT_SA_PASSWORD_SILVER}}
 
       #Build and push image to OpenShift Image stream - Silver
-      - name: Build & Push Image to Openshift Image Stream - Silver
-        env:
-          COMPOSE_DOCKER_CLI_BUILD: 1
-          DOCKER_BUILDKIT: 1
-          CONTEXT: .
-          IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE_SILVER}}/jag-pcss-criminal:${{secrets.OPENSHIFT_ENV_TAG}}
-        run: |
-          docker build \
-            --tag ${IMAGE} \
-            ${CONTEXT}
-            docker push ${IMAGE}
+      # - name: Build & Push Image to Openshift Image Stream - Silver
+      #   env:
+      #     COMPOSE_DOCKER_CLI_BUILD: 1
+      #     DOCKER_BUILDKIT: 1
+      #     CONTEXT: .
+      #     IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE_SILVER}}/jag-pcss-criminal:${{secrets.OPENSHIFT_ENV_TAG}}
+      #   run: |
+      #     docker build \
+      #       --tag ${IMAGE} \
+      #       ${CONTEXT}
+      #       docker push ${IMAGE}
       
       # #Login to OpenShift Container Repository - Kamloops (OC PROD)
       # - name: Login to OpenShift Container Repository - Kamloops (OC PROD)
@@ -139,32 +139,32 @@ jobs:
       #       docker push ${IMAGE}
       
       #Login to Openshift using OC SA and Token of respective env. for Pod labelling - Silver
-      - name: Authenticate OC Env Specific SA - Silver
-        uses: redhat-actions/oc-login@v1
-        env:
-          OPENSHIFT_NAMESPACE: ${{secrets.OPENSHIFT_LICENSE_PLATE_SILVER}}-${{ github.event.inputs.env }}
-          OPENSHIFT_USER: ${{secrets.OPENSHIFT_SA_Env_DEPLOYER_NAME}}
-        with:
-          openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL_SILVER}}
-          openshift_token: ${{secrets.OPENSHIFT_SA_ENV_DEPLOYER_TOKEN_SILVER}}
-          namespace: ${OPENSHIFT_NAMESPACE}
+      # - name: Authenticate OC Env Specific SA - Silver
+      #   uses: redhat-actions/oc-login@v1
+      #   env:
+      #     OPENSHIFT_NAMESPACE: ${{secrets.OPENSHIFT_LICENSE_PLATE_SILVER}}-${{ github.event.inputs.env }}
+      #     OPENSHIFT_USER: ${{secrets.OPENSHIFT_SA_Env_DEPLOYER_NAME}}
+      #   with:
+      #     openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL_SILVER}}
+      #     openshift_token: ${{secrets.OPENSHIFT_SA_ENV_DEPLOYER_TOKEN_SILVER}}
+      #     namespace: ${OPENSHIFT_NAMESPACE}
         
-        # Labels the deployment config of the application with release version number to spin up the pods labelled in same version - Silver
-      - name: Labelling DC to release version - Silver
-        env:
-          releaseVersion: ${{ env.releaseVersion }}
-          appName: ${{ github.event.inputs.app }}
-          openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE_SILVER}}-${{ github.event.inputs.env }}
-        run: |
-          oc patch dc ${appName} -n ${openshiftEnvNamespace} --patch '{"spec":{"template":{"metadata":{"labels":{"version":"${{ env.releaseVersion }}.${{ env.gitsha }}"}}}}}'
+      #   # Labels the deployment config of the application with release version number to spin up the pods labelled in same version - Silver
+      # - name: Labelling DC to release version - Silver
+      #   env:
+      #     releaseVersion: ${{ env.releaseVersion }}
+      #     appName: ${{ github.event.inputs.app }}
+      #     openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE_SILVER}}-${{ github.event.inputs.env }}
+      #   run: |
+      #     oc patch dc ${appName} -n ${openshiftEnvNamespace} --patch '{"spec":{"template":{"metadata":{"labels":{"version":"${{ env.releaseVersion }}.${{ env.gitsha }}"}}}}}'
       
-      # Wait to DC rollout to get completed before proceeding next stage - Silver
-      - name: Wait for DC rollout - Silver
-        env:
-          appName: ${{ github.event.inputs.app }}
-          openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE_SILVER}}-${{ github.event.inputs.env }}
-        run: |
-          oc rollout status -n ${openshiftEnvNamespace} dc/${appName} --watch
+      # # Wait to DC rollout to get completed before proceeding next stage - Silver
+      # - name: Wait for DC rollout - Silver
+      #   env:
+      #     appName: ${{ github.event.inputs.app }}
+      #     openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE_SILVER}}-${{ github.event.inputs.env }}
+      #   run: |
+      #     oc rollout status -n ${openshiftEnvNamespace} dc/${appName} --watch
       
       # #Login to Openshift using OC SA and Token of respective env. for Pod labelling - Kamloops (OC PROD)
       # - name: Authenticate OC Env Specific SA - Kamloops (OC PROD)
@@ -222,30 +222,30 @@ jobs:
       #   run: |
       #     oc rollout status -n ${openshiftEnvNamespace} dc/${appName} --watch
 
-      - name: Run Integration Tests
-        env:
-          TEST_STARTER_URL: ${{secrets.TEST_STARTER_URL}}
-          BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
-          BASIC_AUTH_PASS: ${{ secrets.BASIC_AUTH_PASS }}
-        run: |
-          RET=`curl --write-out '%{content_type}' --output TestErrors.zip --request GET --user ${BASIC_AUTH_USER}:${BASIC_AUTH_PASS} --url ${TEST_STARTER_URL}`
-          if [ "$RET" = "application/zip" ]; then
-            echo "Status: Failed Integration Test(s) found!"
-            exit 1
-          fi
-          if [ "$RET" = "application/json" ]; then
-            echo "Status: All Tests Passed"
-          fi
-          if [ "$RET" != "application/zip" ] && [ "$RET" != "application/json" ]; then
-            echo "Received content_type is $RET, was expecting application/json or application/zip"
-            exit 1
-          fi
+      # - name: Run Integration Tests
+      #   env:
+      #     TEST_STARTER_URL: ${{secrets.TEST_STARTER_URL}}
+      #     BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
+      #     BASIC_AUTH_PASS: ${{ secrets.BASIC_AUTH_PASS }}
+      #   run: |
+      #     RET=`curl --write-out '%{content_type}' --output TestErrors.zip --request GET --user ${BASIC_AUTH_USER}:${BASIC_AUTH_PASS} --url ${TEST_STARTER_URL}`
+      #     if [ "$RET" = "application/zip" ]; then
+      #       echo "Status: Failed Integration Test(s) found!"
+      #       exit 1
+      #     fi
+      #     if [ "$RET" = "application/json" ]; then
+      #       echo "Status: All Tests Passed"
+      #     fi
+      #     if [ "$RET" != "application/zip" ] && [ "$RET" != "application/json" ]; then
+      #       echo "Received content_type is $RET, was expecting application/json or application/zip"
+      #       exit 1
+      #     fi
 
-      - name: Archive production artifacts
-        uses: actions/upload-artifact@v3.1.1
-        if: failure()
-        with:
-          name: integration-tests-report
-          path: |
-            TestErrors.zip
-          retention-days: 5
+      # - name: Archive production artifacts
+      #   uses: actions/upload-artifact@v3.1.1
+      #   if: failure()
+      #   with:
+      #     name: integration-tests-report
+      #     path: |
+      #       TestErrors.zip
+      #     retention-days: 5
